.TH TecnoballZ 6 "TecnoballZ" "2005" "TLK Games"
.SH NAME
tecnoballz - Un jeu de casse-briques.
.SH SYNOPSIS
  tecnoballz [options]
.SH DESCRIPTION
TecnoballZ est un casse briques qui a d'abbord été écrit pour Amiga en 1991. 
.P
Dans Tecnoballz, vous devez casser toutes les briques de chaque niveau.
Le jeu est divisé en zones (Area) lesquelles sont divisées en niveaux (Levels).
Entre certains niveaux, vous devrez battre des gardiens pour passer au niveau suivant.
Lorsque vous passez à une nouvelle zone, un autre côté du jeu s'ouvre.
Vous pouvez acheter des armes et des bonus entre chaque niveau avec l'argent gagné surant le jeu.
.SH KEYBINDINGS
.B Ctrl S
Active ou désactive le son pendant le jeu.
.TP 
. B Ctrl X 
Provoque une abadon de partie (Game Over).
.TP
.B ESC
Revient au menu.
.TP
.B P
Passe le jeu en pause / réactive le jeu.
.SH OPTIONS
.P
.B \--help
Affiche un court message d'aide.
.TP
.B \--version
Affiche le numéro de version et quelques informations.
.TP
.B \--full
Lance le jeu en plein-écran (Dépend de votre configuration X).
.TP
.B \--320|--640
Force la résolution du jeu en 320x200 ou en 640x480 (Dépend de votre configuration de X).
.TP
.B \--verbose
Affiche beaucoup de messages de debugging à l'écran.
.TP
.B \--nosound
Désactive le son.
.SH COPYRIGHT
.if n TecnoballZ est sous Copyright (C) 1992-2004 de la société Tlk Games.
.SH AUTHOR
TLK Games, http://linux.tlk.fr
.P
Bruno Ethvignot, developement et portage Linux.
.P
Cette page de mannuel a été écrite par Alexis Sukrieh <sukria@sukria.net> 
pour le système Debian (mais peut être utilisée pour d'autres).  

