#!/bin/sh

set -ex

rm -f aclocal.m4 configure config.log
mkdir -p autotools
(cd autotools && rm -f config.guess config.sub depcomp install-sh missing mkinstalldirs)

aclocal
automake -a -c --foreign
autoconf
autoheader
