.TH TecnoballZ
.SH NAME
tecnoballz - A Breakout like game.
.SH SYNOPSIS
  tecnoballz [options]
.SH DESCRIPTION
TecnoballZ is a "breaking blocks" game that was first written for the Amiga 
platform.
.P
You'll need to break all the blocks in each level. The game is divided into 
Areas which are divided into Levels.
Between some levels, you have to defeat a guardian to pass to the next level.
When passing an Area, a new edge is open. You can buy weapons and bonus between
levels with the money earned during the game.
.SH KEYBINDINGS
.B [Space]
Release ball(s)
.TP
.B Left [Ctrl]
Fire
.TP
.B Left [Alt]
Fire Gigablitz or activate the tilt
.TP
.B [Ctrl] + [S]
Toggle sound activation.
.TP 
. B [Ctrl] + [X] 
Causes a game over.
.TP
.B [ESC]
Go to the menu.
.TP
.B [P]
Toggle pause.
.TP
.B [PAGE UP]
Volume up
.TP
.B [PAGE DOWN]
Volume down
.SH OPTIONS
.P
.B \--help
Display a short help message.
.TP
.B \--version
Display version number.
.TP
.B \--full
Start the game in fullscreen mode.
.TP
.B \--320|--640
Force the game resolution to 320x200 or 640x480.
.TP
.B \--verbose
Print a lot of debuging information to stdout.
.TP
.B \--nosound
Disable the sound.
.SH COPYRIGHT
.if n TecnoballZ is Copyright (C) 1992-2008 by the TLK Games Company.
.SH AUTHOR
TLK Games, http://linux.tlk.fr/games/TecnoballZ/
.P
Bruno Ethvignot, development and Linux port.
.P
This man-page was written by Alexis Sukrieh <sukria@sukria.net> 
for  the  Debian  system (but may be used by others).  

